version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"    # AMQP clients
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Guarantees data persistence
      
  postgres:
    imagen: postgres:15
    container_name: postgres
    restart: always                     # Restart container if it stops
    environment:
      POSTGRES_USER: weather_user       # User that creates the database
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather              # Database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Guarantees data persistence
      - ./postgres/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro # Initialize the database with a script 

# producer:
# consumer:

volumes:
  rabbitmq_data:
  postgres_data:
